<?php


/**
 * Prepares variables for image gallery item templates.
 *
 * Default template: image-gallery-item.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - item: An ImageItem object.
 *   - item_attributes: An optional associative array of html attributes to be
 *     placed in the img tag.
 *   - image_style: An optional image style.
 *   - url: An optional \Drupal\Core\Url object.
 */
function template_preprocess_image_gallery_item_formatter(&$variables)
{

}
